/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddonGallery: typeof import('./.vitepress/theme/components/AddonGallery.vue')['default']
    AddonInfo: typeof import('./.vitepress/theme/components/AddonInfo.vue')['default']
    Arrow: typeof import('./node_modules/@slidev/client/builtin/Arrow.vue')['default']
    AutoFitText: typeof import('./node_modules/@slidev/client/builtin/AutoFitText.vue')['default']
    CodeBlockWrapper: typeof import('./node_modules/@slidev/client/builtin/CodeBlockWrapper.vue')['default']
    Demo: typeof import('./.vitepress/theme/components/Demo.vue')['default']
    DemoEditor: typeof import('./.vitepress/theme/components/DemoEditor.vue')['default']
    DemoSlide: typeof import('./.vitepress/theme/components/DemoSlide.vue')['default']
    Environment: typeof import('./.vitepress/theme/components/Environment.vue')['default']
    FeaturesAnimation: typeof import('./.vitepress/theme/components/FeaturesAnimation.vue')['default']
    FeaturesAnimationInner: typeof import('./.vitepress/theme/components/FeaturesAnimationInner.vue')['default']
    FeaturesOverview: typeof import('./.vitepress/theme/components/FeaturesOverview.vue')['default']
    FeatureTag: typeof import('./.vitepress/theme/components/FeatureTag.vue')['default']
    KaTexBlockWrapper: typeof import('./node_modules/@slidev/client/builtin/KaTexBlockWrapper.vue')['default']
    LandingPage: typeof import('./.vitepress/theme/components/LandingPage.vue')['default']
    Layout: typeof import('./.vitepress/theme/components/Layout.vue')['default']
    LightOrDark: typeof import('./node_modules/@slidev/client/builtin/LightOrDark.vue')['default']
    Link: typeof import('./node_modules/@slidev/client/builtin/Link.vue')['default']
    LinkCard: typeof import('./.vitepress/theme/components/LinkCard.vue')['default']
    LinkInline: typeof import('./.vitepress/theme/components/LinkInline.vue')['default']
    Mermaid: typeof import('./node_modules/@slidev/client/builtin/Mermaid.vue')['default']
    Monaco: typeof import('./node_modules/@slidev/client/builtin/Monaco.vue')['default']
    PlantUml: typeof import('./node_modules/@slidev/client/builtin/PlantUml.vue')['default']
    PoweredBySlidev: typeof import('./node_modules/@slidev/client/builtin/PoweredBySlidev.vue')['default']
    RenderWhen: typeof import('./node_modules/@slidev/client/builtin/RenderWhen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeeAlso: typeof import('./.vitepress/theme/components/SeeAlso.vue')['default']
    ShikiMagicMove: typeof import('./node_modules/@slidev/client/builtin/ShikiMagicMove.vue')['default']
    ShowCaseInfo: typeof import('./.vitepress/theme/components/ShowCaseInfo.vue')['default']
    ShowCases: typeof import('./.vitepress/theme/components/ShowCases.vue')['default']
    SlideContainer: typeof import('./.vitepress/theme/components/SlideContainer.vue')['default']
    SlideCurrentNo: typeof import('./node_modules/@slidev/client/builtin/SlideCurrentNo.vue')['default']
    SlidesTotal: typeof import('./node_modules/@slidev/client/builtin/SlidesTotal.vue')['default']
    SlidevVideo: typeof import('./node_modules/@slidev/client/builtin/SlidevVideo.vue')['default']
    ThemeGallery: typeof import('./.vitepress/theme/components/ThemeGallery.vue')['default']
    ThemeInfo: typeof import('./.vitepress/theme/components/ThemeInfo.vue')['default']
    TheTweet: typeof import('./.vitepress/theme/components/TheTweet.vue')['default']
    Toc: typeof import('./node_modules/@slidev/client/builtin/Toc.vue')['default']
    TocList: typeof import('./node_modules/@slidev/client/builtin/TocList.vue')['default']
    Transform: typeof import('./node_modules/@slidev/client/builtin/Transform.vue')['default']
    Tweet: typeof import('./node_modules/@slidev/client/builtin/Tweet.vue')['default']
    VClickGap: typeof import('./node_modules/@slidev/client/builtin/VClickGap.vue')['default']
    VDrag: typeof import('./node_modules/@slidev/client/builtin/VDrag.vue')['default']
    VDragArrow: typeof import('./node_modules/@slidev/client/builtin/VDragArrow.vue')['default']
    Youtube: typeof import('./node_modules/@slidev/client/builtin/Youtube.vue')['default']
  }
}
